#!/bin/bash
if [ -z "$CONFDIR" ] || [ -z "$BINDIR" ] || [ -z "$MAEDIR" ] || [ -z "$NOVEDIR"] || [ -z "$ACEPDIR"] || [ -z "$PROCDIR"] || [ -z "$REPODIR"] || [ -z "$LOGDIR" ] || [ -z "$RECHDIR" ]; then
	return 1
else
	pid=$(ps aux | grep $1 | grep -v 'Arrancar' | grep -v 'grep' | head -n 1 | awk '{print $2}')
	if [ -z $pid ]; then
		./$1 &
		return 0
	else
		return 1
	fi
fi

