#!/bin/bash
if [ -z "$CONFDIR" ] || [ -z "$BINDIR" ] || [ -z "$MAEDIR" ] ||
	[ -z "$NOVEDIR"] || [ -z "$ACEPDIR"] || [ -z "$PROCDIR"] ||
	[ -z "$REPODIR"] || [ -z "$LOGDIR" ] || [ -z "$RECHDIR" ]; then
	[ -z "$AFRARECIRUN" ] || [ -z "$AFRAUMBRRUN" ] || [ -z "$AFRALISTRUN" ]; then
		echo "error"
	else
		if [ -z "\$$1RUN" ]; then
			$BINDIR/$@
		else
			echo "error"
		fi
	fi

