#!/bin/bash
function log {
	message=""
	if [ -z "$command" ];then
		command="MoverA"
	else
		message="usando MoverA "
	fi
	if [ $1 == 1 ];then
		$BINDIR/GraLog "$command" "${message}no puedes mover un archivo a su mismo directorio" "ERROR"
	fi
	if [ $1 == 2 ];then
		$BINDIR/GraLog "$command" "${message}el archivo de origen no existe" "ERROR"
	fi
	if [ $1 == 3 ];then
		$BINDIR/GraLog "$command" "${message}el directorio de destino no existe" "ERROR"
	fi
}
origin=$1
destiny=$2
command=$3
lastchar="${destiny:((${#destiny}-1)):1}"
if [ $lastchar != "/" ];then
	destiny="$destiny/"
fi
filename=$(basename "$origin")
filedir=$(dirname "$origin")
filedir="$filedir/"
if [ "$filedir" == "$destiny" ];then
	log 1
	return 1
fi
if [ -f "$origin" ] && [ -d "$destiny" ];then
	duplicate=$destiny$filename
	if [ -f "$duplicate" ];then
		if [ ! -d "${destiny}duplicates" ];then
			mkdir "${destiny}duplicates"
		fi
		duplicate=${destiny}duplicates/${filename}
		if [ ! -f ${duplicate}.001 ];then
			mv "$origin" "${duplicate}.001"
		else
			extension=(${duplicate}.*)
			extension=${#extension[@]}
			let "extension++"
			extension=$(printf '%03d' $extension)
			mv "$origin" "${duplicate}.${extension}"
		fi
	else
		mv "$origin" "$duplicate"
	fi
else
	if [ ! -f "$origin" ];then
		log 2
		return 2		
	fi
	if [ ! -d "$destiny" ];then
		log 3
		return 3
	fi
fi
